name: belajar_dart_packages_app
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'


publish_to: none
dependencies:
  dart_packages_library_pzn:
    git:
      url: https://github.com/djoemsa/dart_packages_library_pzn.git
      ref: 1.5.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
